name: GROUP5.CSV.SIRVs.R10
output: /abga/work/andreyp/ci_isoquant/output
run_type: transcripts
genome: /abga/work/andreyp/ci_isoquant/data/ref/SIRV4/SIRV_isoforms_multi-fasta_200709a.fasta
genedb: /abga/work/andreyp/ci_isoquant/data/ref/SIRV4/SIRV_isoforms_multi-fasta-annotation.reduced.gtf
bam: /abga/work/andreyp/ci_isoquant/data/groups/Lexogen.SIRVs.Set4.ONT_cDNA.R10.4.sorted.bam
datatype: ont
isoquant_options: '"-t 8 --complete_genedb --force --read_group file:/abga/work/andreyp/ci_isoquant/data/groups/Lexogen.SIRVs.Set4.ONT_cDNA.R10.4.grouped.groups.csv:0:1:,
  "'
reduced_db: /abga/work/andreyp/ci_isoquant/data/ref/SIRV4/SIRV_isoforms_multi-fasta-annotation
check_input_files: gene_grouped_file0_col1_counts.linear.tsv transcript_grouped_file0_col1_counts.linear.tsv discovered_transcript_grouped_file0_col1_counts.linear.tsv gene_grouped_file0_col1_tpm.tsv transcript_grouped_file0_col1_tpm.tsv
baselines:
  transcripts:
    full_recall: 76.8
    full_precision: 100.0
    known_recall: 97.7
    known_precision: 100.0
    novel_recall: 42.3
    novel_precision: 100.0
