name: GROUP4.FILES.SIRVs.R10
output: /abga/work/andreyp/ci_isoquant/output
run_type: transcripts
genome: /abga/work/andreyp/ci_isoquant/data/ref/SIRV4/SIRV_isoforms_multi-fasta_200709a.fasta
genedb: /abga/work/andreyp/ci_isoquant/data/ref/SIRV4/SIRV_isoforms_multi-fasta-annotation.reduced.gtf
datatype: ont
isoquant_options: '"-t 8 --complete_genedb --force --read_group file_name --bam /abga/work/andreyp/ci_isoquant/data/groups/Lexogen.SIRVs.Set4.ONT_cDNA.R10.4.grouped.group0.bam
  /abga/work/andreyp/ci_isoquant/data/groups/Lexogen.SIRVs.Set4.ONT_cDNA.R10.4.grouped.group1.bam
  --count_exons "'
check_input_files: gene_grouped_file_name_counts.linear.tsv transcript_grouped_file_name_counts.linear.tsv discovered_transcript_grouped_file_name_counts.linear.tsv gene_grouped_file_name_tpm.tsv transcript_grouped_file_name_tpm.tsv exon_grouped_file_name_counts.linear.tsv splice_junction_grouped_file_name_counts.linear.tsv
reduced_db: /abga/work/andreyp/ci_isoquant/data/ref/SIRV4/SIRV_isoforms_multi-fasta-annotation
baselines:
  transcripts:
    full_recall: 76.8
    full_precision: 100.0
    known_recall: 97.7
    known_precision: 100.0
    novel_recall: 42.3
    novel_precision: 100.0
