name: Human.ONT_simulated.TSS
output: /abga/work/andreyp/ci_isoquant/output
run_type: transcripts,tss_prediction
genome: /abga/work/andreyp/data/reference/human/GRCh38.primary_assembly.genome.fa
genedb: /abga/work/andreyp/data/reference/human/gencode.v44.annotation.gtf.db
bam: /abga/work/andreyp/ci_isoquant/data/human_tss/OUT_simulated_aligned_reads_human_5502a8_9831b5_093b11.bam
simulated_counts: /abga/work/andreyp/ci_isoquant/data/human_tss/quantified_tr_human_tss_1.tsv
reference_tss_gtf: /abga/work/andreyp/ci_isoquant/data/human_tss/updated_human_tss_1.gtf
reduced_db: /abga/work/andreyp/ci_isoquant/data/simulated_truth/Human.ONT_simulated.TSS
datatype: ont
isoquant_options: '"-t 16 --complete_genedb --force --fl_data
  "'
baselines:
  transcripts:
    full_recall: 84.9
    full_precision: 96.3
    known_recall: 95.0
    known_precision: 89.6
    novel_recall: 50.4
    novel_precision: 94.7
  transcripts_td50:
    full_recall: 82.5
    full_precision: 93.6
    known_recall: 94.9
    known_precision: 89.6
    novel_recall: 50.2
    novel_precision: 94.3
  transcripts_td10:
    full_recall: 77.3
    full_precision: 87.7
    known_recall: 94.9
    known_precision: 89.6
    novel_recall: 44.9
    novel_precision: 84.4
  tss_prediction:
    precision: 97.7606
    recall: 70.0891
    precision_known: 97.3647
    recall_known: 65.4734
    precision_novel: 98.4814
    recall_novel: 80.2744
