name: RESUME1.SIRVs.R10
label: SRIV.Set4.ONT_R10
output: /abga/work/andreyp/ci_isoquant/output
resume: /abga/work/andreyp/ci_isoquant/data/resume/SRIV.Set4.ONT_R10.resume1
run_type: transcripts
reduced_db: /abga/work/andreyp/ci_isoquant/data/ref/SIRV4/SIRV_isoforms_multi-fasta-annotation
baselines:
  transcripts:
    full_recall: 76.8
    full_precision: 100.0
    known_recall: 97.7
    known_precision: 100.0
    novel_recall: 42.3
    novel_precision: 100.0
