name: SIRVs.simulated_perfect_polya
output: /abga/work/andreyp/ci_isoquant/output
run_type: transcripts
genome: /abga/work/andreyp/ci_isoquant/data/ref/SIRV4/SIRV_isoforms_multi-fasta_200709a.fasta
genedb: /abga/work/andreyp/ci_isoquant/data/ref/SIRV4/SIRV_isoforms_multi-fasta-annotation.reduced.gtf
reads: /abga/work/andreyp/simulation/sirvs/SIRV.perfect.artificial_exp.polyA.no_trunc_aligned_reads.fasta
datatype: ont
isoquant_options: '"-t 6 --complete_genedb --force "'
reduced_db: /abga/work/andreyp/ci_isoquant/data/ref/SIRV4/SIRV_isoforms_multi-fasta-annotation
baselines:
  transcripts:
    full_recall: 69.6
    full_precision: 100.0
    known_recall: 95.3
    known_precision: 100.0
    novel_recall: 26.9
    novel_precision: 100.0
  transcripts_td50:
    full_recall: 69.6
    full_precision: 100.0
    known_recall: 95.3
    known_precision: 100.0
    novel_recall: 26.9
    novel_precision: 100.0
  transcripts_td10:
    full_recall: 68.1
    full_precision: 97.9
    known_recall: 95.3
    known_precision: 100.0
    novel_recall: 23.1
    novel_precision: 85.7
