name: Mouse.10x.5k.no_truncation.ONT
output: /abga/work/andreyp/ci_isoquant/output
run_type: single
reads: Mouse.10x.5k.no_truncation.NewStereoQ.600k.fq.gz
barcodes: 10xMultiome_5K.tsv
mode: tenX_v3
threads: '8'
qa_mode: tenX_v3
baselines:
  barcode:
    barcoded_reads: 525507.0
    correct_barcodes: 524095.0
    precision: 99.73
    precision_at_11: 99.73
    precision_at_12: 99.73
    precision_at_13: 99.73
    precision_at_14: 99.73
    precision_at_15: 99.96
    precision_at_16: 100.0
    recall: 87.35
    recall_at_11: 87.35
    recall_at_12: 87.35
    recall_at_13: 87.35
    recall_at_14: 87.35
    recall_at_15: 79.72
    recall_at_16: 75.6
    total_reads: 600000.0
    umi_within_1: 483340.0
    umi_within_2: 500190.0
    umi_within_3: 511720.0
    unique_detected_barcodes: 5000.0
    unique_true_barcodes: 5000.0
