name: SIRVs real ONT no annotation

on:
  workflow_dispatch:
  schedule:
  - cron: '0 12 * * 0,2,4'

env:
  RUN_NAME: SIRVs.Set4.R10
  LAUNCHER: ${{github.workspace}}/tests/github/run_pipeline.py
  CFG_DIR: /abga/work/andreyp/ci_isoquant/data
  BIN_PATH: /abga/work/andreyp/ci_isoquant/bin/
  OUTPUT_BASE: /abga/work/andreyp/ci_isoquant/output/${{github.ref_name}}/

concurrency:
  group: ${{github.workflow}}
  cancel-in-progress: false

jobs:
  launch-runner:
    runs-on:
      labels: [isoquant]
    name: 'Running IsoQuant and QC'

    steps:
      - name: 'Cleanup'
        run: >
          set -e &&
          shopt -s dotglob &&
          rm -rf *

      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: 'IsoQuant SIRVs R10.4 no GTF'
        if: always()
        shell: bash
        env:
          STEP_NAME: SIRVs.Set4.R10.noGTF
        run: |
          export PATH=$PATH:${{env.BIN_PATH}}
          python3 ${{env.LAUNCHER}} ${{env.CFG_DIR}}/${{env.STEP_NAME}}.cfg -o ${{env.OUTPUT_BASE}}

      - name: 'IsoQuant SIRVs R9.4 no GTF'
        if: always()
        shell: bash
        env:
          STEP_NAME: SIRVs.Set4.R9.noGTF
        run: |
          export PATH=$PATH:${{env.BIN_PATH}}
          python3 ${{env.LAUNCHER}} ${{env.CFG_DIR}}/${{env.STEP_NAME}}.cfg -o ${{env.OUTPUT_BASE}}
